class AuditReport:

    @staticmethod
    def generate(report: dict):

        invoice = report.get("invoice", {})
        validation = report.get("validation", {})
        risk = report.get("risk", {})
        recommendations = report.get("recommendations", [])

        output = []

        output.append("=" * 60)
        output.append("              TAXSARTHI AI AUDIT REPORT")
        output.append("=" * 60)

        output.append("")
        output.append("INVOICE DETAILS")
        output.append("-" * 60)

        output.append(
            f"Invoice Number : {invoice.get('invoice_number')}"
        )

        output.append(
            f"Invoice Date   : {invoice.get('invoice_date')}"
        )

        output.append(
            f"Supplier       : {invoice.get('supplier')}"
        )

        output.append(
            f"Buyer          : {invoice.get('buyer')}"
        )

        output.append(
            f"GSTIN          : {invoice.get('supplier_gstin')}"
        )

        output.append(
            f"Total Amount   : {invoice.get('total_amount')}"
        )

        output.append("")
        output.append("RISK ANALYSIS")
        output.append("-" * 60)

        output.append(
            f"Risk Score : {risk.get('score')}/100"
        )

        output.append(
            f"Risk Level : {risk.get('level')}"
        )

        output.append("")

        output.append("VALIDATION ERRORS")
        output.append("-" * 60)

        errors = validation.get("errors", [])

        if errors:

            for error in errors:

                output.append(f"❌ {error}")

        else:

            output.append("✅ No validation errors.")

        output.append("")
        output.append("RECOMMENDATIONS")
        output.append("-" * 60)

        if recommendations:

            for rec in recommendations:

                output.append(
                    f"[{rec['priority']}] {rec['recommendation']}"
                )

        else:

            output.append("No recommendations.")

        output.append("")
        output.append("=" * 60)
        output.append("Generated by TaxSarthi AI")
        output.append("=" * 60)

        return "\n".join(output)